### ISSUE TITLE
It Crashing afer place the Fluid Port in the World

### ISSUE THREAD

**Issue by GalaxyOfZero** [TicTicBoooom-Mods/MasterfulMachinery#38] opened 2022-08-28 12:38 UTC
# Version Information
Forge version:  36.2.29
Masterful Machinery version: 1.16.5-0.1.64-b975

ADD ON'S
if not installed just put "null"
Optifine version: "null"
Botania version:  1.16.5-420.2
Create version: 1.16.5-v.0.3.2g
Mekanism version: 1.16.5-10.1.2.457
Pneumaticcraft version: "null"
Astral Sorcery version: 1.16.5-1.14.1

# Further Information
[crash-2022-08-28_14.18.01-client.txt](https://github.com/TicTicBoooom-Mods/MasterfulMachinery/files/9439653/crash-2022-08-28_14.18.01-client.txt)
[crash-2022-08-28_14.21.38-client.txt](https://github.com/TicTicBoooom-Mods/MasterfulMachinery/files/9439654/crash-2022-08-28_14.21.38-client.txt)
[crash-2022-08-28_14.27.59-client.txt](https://github.com/TicTicBoooom-Mods/MasterfulMachinery/files/9439655/crash-2022-08-28_14.27.59-client.txt)

What I expected to happen:
Im the Dev from the Modpack Skyfriends and i and do use the mod masterful Masterful Machinery, by building the Multiblock the game crasht every time i load up the World and i dont no why.

- Building test Multiblock Blood Converter

What happened instead:
after place the fluid input the game is crashing by loading the world

**Comment by MasterSloth1** [comment] 2022-08-28 13:11
could you post your config file please

**Comment by GalaxyOfZero** [comment] 2022-08-28 13:15
the Controller Data:
`{
  "controllerId": "blood_converter",
  "name": "Blood Converter",
  "ports": [
    {
      "type": "masterfulmachinery:items",
      "name": "Item Port",
      "id": "items",
      "data": {
        "rows": 1,
        "columns": 1
      }
    },
    {
      "type": "masterfulmachinery:fluids",
      "name": "Fluid Port",
      "id": "fluids",
      "data": {
         "capacity ": 50000
      }
    }
  ]
}`

**Comment by MasterSloth1** [comment] 2022-08-28 13:22
you have a space at the end of capacity

**Comment by ticticboooom** [comment] 2022-08-28 13:26
Not a bug, confirmed user error. closing as it was opened against policy

**Closed by ticticboooom** 2022-08-28 13:26 UTC
Labels: bug

**Comment by GalaxyOfZero** [comment] 2022-08-28 13:39
SOOO i go to all of my confings and it has no problems via https://jsonformatter.curiousconcept.com.
but the crash by placing the Fluid Port remains!

[crash-2022-08-28_15.35.32-client.txt](https://github.com/TicTicBoooom-Mods/MasterfulMachinery/files/9439743/crash-2022-08-28_15.35.32-client.txt)
[crash-2022-08-28_15.30.07-client.txt](https://github.com/TicTicBoooom-Mods/MasterfulMachinery/files/9439744/crash-2022-08-28_15.30.07-client.txt)

if your mean is a space at the end of capacity, it is not it !!
![image](https://user-images.githubusercontent.com/57020876/187076724-e06848b4-942f-4c94-9094-ef0089aea650.png)
 
 pls tell me what is the problem!!!!

**Comment by ticticboooom** [comment] 2022-08-28 13:41
@MasterSloth1 already told you: you have a space in the json key capacity

**Comment by MasterSloth1** [comment] 2022-08-28 13:41
the json formater wont have a issue with the problem because its a string, strings can be anything, but for masterful machinery it is looking for a specific string so by having the space at the end it wont recognize that string

**Comment by ticticboooom** [comment] 2022-08-28 13:45
please join our discord server: https://discord.gg/NCSRkkPbmF we can help you a lot easier there
